esphome:
  name: stoplight

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8kg+Elb/5Kh3ADFI0VDRXHXrlFEC4J2sm9uGyewsYdI="

ota:
  password: "64125a93f7c75343e2d4da45ac0602a9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stoplight Fallback Hotspot"
    password: "psYjlUmHYhgl"

captive_portal:

light:
  - platform: binary
    name: "Green Light"
    output: green_led
  - platform: binary
    name: "Yellow Light"
    output: yellow_led
  - platform: binary
    name: "Red Light"
    output: red_led

output:
  - id: green_led
    platform: gpio
    pin: GPIO0
  - id: yellow_led
    platform: gpio
    pin: GPIO4
  - id: red_led
    platform: gpio
    pin: GPIO5